#353 - Customizable auth scheme
artipie/docker-adapter pull request #379
Opened 2020-12-03 10:03 UTC by olegmoz

Closes #353 
Customizable auth scheme

2020-12-03 11:29 UTC, genryxy requested changes
@olegmoz thanks, please see the comments

2020-12-03 11:29 UTC, genryxy commented on src/test/java/com/artipie/docker/http/AuthTest.java
> +        }
@olegmoz I'd suggest to use `BasicAuthScheme.NAME` instead of string value

2020-12-03 11:29 UTC, genryxy commented on src/test/java/com/artipie/docker/http/AuthTest.java
> +        }
@olegmoz and here use `BearerAuthScheme.NAME` instead of string value

2020-12-03 13:11 UTC, olegmoz commented on src/test/java/com/artipie/docker/http/AuthTest.java
> +        }
@genryxy thanks, but I'd prefer not to do that. It will create a dependency when it is not really here. Yes, the strings are the same, but their origin and usage is very different. `BasicAuthScheme.NAME` is exact name of authentication scheme specified in RFC. And here is just `toString` result used to make JUnit runner's output more clear when it prints tests arguments.

2020-12-03 13:29 UTC, genryxy approved these changes
@olegmoz thanks, approve

2020-12-03 13:29 UTC, genryxy commented on src/test/java/com/artipie/docker/http/AuthTest.java
> +        }
@olegmoz understood, thanks for the explanation

2020-12-03 14:33 UTC, merged

2020-12-04 09:39 UTC, olegmoz commented
@rultor release, tag=`0.8`

2020-12-04 09:39 UTC, rultor commented
> @rultor release, tag=`0.8`

@olegmoz OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23815-738680882)

2020-12-04 10:12 UTC, rultor commented
> @rultor release, tag=`0.8`

@olegmoz Oops, I failed. You can see the full log [here](https://www.rultor.com/t/23815-738680882) (spent 33min)

```
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: com.sonatype.nexus.staging.client.StagingRuleFailuresException: \u001b[1;31mStaging rules failure!\u001b[m
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl.monitorRepositoryTransition (\u001b[1mStagingWorkflowV3ServiceImpl.java:205\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl$9.perform (\u001b[1mStagingWorkflowV2ServiceImpl.java:247\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl$9.perform (\u001b[1mStagingWorkflowV2ServiceImpl.java:242\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.ExceptionConverter.runAndReturn (\u001b[1mExceptionConverter.java:38\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl.dropStagingRepositories (\u001b[1mStagingWorkflowV2ServiceImpl.java:241\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.strategy.AbstractStagingDeployStrategy.afterUploadFailure (\u001b[1mAbstractStagingDeployStrategy.java:287\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.strategy.StagingDeployStrategy.finalizeDeploy (\u001b[1mStagingDeployStrategy.java:153\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.DeployMojo.execute (\u001b[1mDeployMojo.java:213\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
container 8a53266f81bda3e0e0ec5f20a1df9b35721022047379913c6a4a4b192e7ef89c is dead
Fri Dec  4 11:12:43 CET 2020
```

2020-12-04 10:17 UTC, olegmoz commented
@rultor release, tag=`0.8`

2020-12-04 10:18 UTC, rultor commented
> @rultor release, tag=`0.8`

@olegmoz OK, I will release it now. Please check the progress [here](https://www.rultor.com/t/23815-738699853)

2020-12-04 10:50 UTC, rultor commented
> @rultor release, tag=`0.8`

@olegmoz Oops, I failed. You can see the full log [here](https://www.rultor.com/t/23815-738699853) (spent 32min)

```
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
\u001b[1mCaused by\u001b[m: com.sun.jersey.api.client.ClientHandlerException: \u001b[1;31mA message body reader for Java class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and Java type class com.sonatype.nexus.staging.api.dto.StagingProfileRepositoryDTO, and MIME media type text/html was not found\u001b[m
    \u001b[1mat\u001b[m com.sun.jersey.api.client.ClientResponse.getEntity (\u001b[1mClientResponse.java:561\u001b[m)
    \u001b[1mat\u001b[m com.sun.jersey.api.client.ClientResponse.getEntity (\u001b[1mClientResponse.java:517\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl$1.perform (\u001b[1mStagingWorkflowV3ServiceImpl.java:80\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl$1.perform (\u001b[1mStagingWorkflowV3ServiceImpl.java:68\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.ExceptionConverter.runAndReturn (\u001b[1mExceptionConverter.java:38\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl.findRepository (\u001b[1mStagingWorkflowV3ServiceImpl.java:67\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV3ServiceImpl.monitorRepositoryTransition (\u001b[1mStagingWorkflowV3ServiceImpl.java:213\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl$9.perform (\u001b[1mStagingWorkflowV2ServiceImpl.java:247\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl$9.perform (\u001b[1mStagingWorkflowV2ServiceImpl.java:242\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.ExceptionConverter.runAndReturn (\u001b[1mExceptionConverter.java:38\u001b[m)
    \u001b[1mat\u001b[m com.sonatype.nexus.staging.client.internal.StagingWorkflowV2ServiceImpl.dropStagingRepositories (\u001b[1mStagingWorkflowV2ServiceImpl.java:241\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.strategy.AbstractStagingDeployStrategy.afterUploadFailure (\u001b[1mAbstractStagingDeployStrategy.java:287\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.strategy.StagingDeployStrategy.finalizeDeploy (\u001b[1mStagingDeployStrategy.java:153\u001b[m)
    \u001b[1mat\u001b[m org.sonatype.nexus.maven.staging.deploy.DeployMojo.execute (\u001b[1mDeployMojo.java:213\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.plugin.DefaultBuildPluginManager.executeMojo (\u001b[1mDefaultBuildPluginManager.java:137\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:210\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:156\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.MojoExecutor.execute (\u001b[1mMojoExecutor.java:148\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:117\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleModuleBuilder.buildProject (\u001b[1mLifecycleModuleBuilder.java:81\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.builder.singlethreaded.SingleThreadedBuilder.build (\u001b[1mSingleThreadedBuilder.java:56\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.lifecycle.internal.LifecycleStarter.execute (\u001b[1mLifecycleStarter.java:128\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:305\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.doExecute (\u001b[1mDefaultMaven.java:192\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.DefaultMaven.execute (\u001b[1mDefaultMaven.java:105\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.execute (\u001b[1mMavenCli.java:956\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.doMain (\u001b[1mMavenCli.java:288\u001b[m)
    \u001b[1mat\u001b[m org.apache.maven.cli.MavenCli.main (\u001b[1mMavenCli.java:192\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke0 (\u001b[1mNative Method\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.NativeMethodAccessorImpl.invoke (\u001b[1mNativeMethodAccessorImpl.java:62\u001b[m)
    \u001b[1mat\u001b[m jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke (\u001b[1mDelegatingMethodAccessorImpl.java:43\u001b[m)
    \u001b[1mat\u001b[m java.lang.reflect.Method.invoke (\u001b[1mMethod.java:566\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launchEnhanced (\u001b[1mLauncher.java:282\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.launch (\u001b[1mLauncher.java:225\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.mainWithExitCode (\u001b[1mLauncher.java:406\u001b[m)
    \u001b[1mat\u001b[m org.codehaus.plexus.classworlds.launcher.Launcher.main (\u001b[1mLauncher.java:347\u001b[m)
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] Re-run Maven using the \u001b[1m-X\u001b[m switch to enable full debug logging.
[\u001b[1;31mERROR\u001b[m] 
[\u001b[1;31mERROR\u001b[m] For more information about the errors and possible solutions, please read the following articles:
[\u001b[1;31mERROR\u001b[m] \u001b[1m[Help 1]\u001b[m http://cwiki.apache.org/confluence/display/MAVEN/PluginExecutionException
container 92adfc4733b94258dee1d054f0c7b84fcc090fa451c45ed0d7d9f3235c3c0985 is dead
Fri Dec  4 11:50:51 CET 2020
```