#373 - Added AstoTags
artipie/docker-adapter pull request #381
Opened 2020-12-04 12:28 UTC by olegmoz

Part of #373
Added `AstoTags`

2020-12-04 13:16 UTC, genryxy requested changes
@olegmoz thanks, one suggestion

2020-12-04 13:16 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz maybe here use `do{ } while()` instead of `while(true) { break }`

2020-12-04 13:27 UTC, olegmoz commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@genryxy I agree that generally `do{ } while()` is better then `while(true) { break }` and thought about solutions, but could not found any. It is trivial when last expression in condition, but `child = parent.get()` has to be after condition check and this makes the case problematic

2020-12-04 13:39 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz `parent` should be declared at the begin of method and should be not final. And return `new Tag.Valid(parent.get().string()...)`. I may be wrong but it seems to be correct

2020-12-04 14:16 UTC, olegmoz commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@genryxy not sure I understood you correctly, is this something you proposed?
```java
        Key child = key;
        Optional<Key> parent;
        while (
            (parent = child.parent()).map(
                prnt -> !prnt.string().equals(this.root.string())
            ).orElse(true)
        ) {
            if (!parent.isPresent()) {
                throw new IllegalStateException(
                    String.format("Key %s does not belong to root %s", key, this.root)
                );
            }
            child = parent.get();
        }
        return new Tag.Valid(child.string().substring(this.root.string().length() + 1));
```

2020-12-04 14:24 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz something like this
```
       Key child = key;
       Optional<Key> parent;
       do {
            parent = child.parent();
            if (!parent.isPresent()) {
                throw new IllegalStateException(
                    String.format("Key %s does not belong to root %s", key, this.root)
                );
            }
            child = parent.get();
        } while(parent.get().string().equals(this.root.string()))
        return new Tag.Valid(parent.get().string().substring(this.root.string().length() + 1));
```

2020-12-04 14:46 UTC, olegmoz commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@genryxy sorry, but this won't work. Assignment of child variable should not be done if condition is true. It is important that it's placed before condition check in original code.

2020-12-04 14:51 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz yes therefore return
 `new Tag.Valid(parent.get().string().substring(this.root.string().length() + 1));`  unstead of 
`new Tag.Valid(child.string().substring(this.root.string().length() + 1));`

2020-12-04 18:00 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz sorry, you're right. I am wrong, because at first I thought that the values `child` and `parent` are the same at the end.

2020-12-04 18:00 UTC, genryxy approved these changes
@olegmoz thanks, approve

2020-12-04 18:14 UTC, genryxy commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@olegmoz I came up with a solution with flag but I am not sure it better than the existing implementation
```
       Key child = key;
       boolean flag;
       do {
            final Optional<Key> parent = child.parent();
            if (!parent.isPresent()) {
                throw new IllegalStateException(
                    String.format("Key %s does not belong to root %s", key, this.root)
                );
            }
            flag = parent.get().string().equals(this.root.string());
            if (!flag) { 
                 child = parent.get();
            }
        } while(!flag)
        return new Tag.Valid(child.string().substring(this.root.string().length() + 1));
```

2020-12-07 07:38 UTC, olegmoz commented on src/main/java/com/artipie/docker/asto/AstoTags.java
> +        }
@genryxy yes, this approach with `flag` does not look like better solution

2020-12-07 07:38 UTC, merged