(#216) - Handle status in ProxyBlob.content
artipie/docker-adapter pull request #495
Opened 2021-11-08 18:43 UTC by andreoss

Per #216

2021-11-09 09:16 UTC, g4s8 requested changes
@andreoss looks good, please check one comment. Also, please fix PR description: add a short description of your solution to put it into the git history log.

2021-11-09 09:16 UTC, g4s8 commented on src/main/java/com/artipie/docker/proxy/ProxyBlob.java
> +                    )).toCompletableFuture();
Let's use `ArtipieHttpException` here: https://github.com/artipie/http/blob/master/src/main/java/com/artipie/http/ArtipieHttpException.java

2021-11-09 14:00 UTC, andreoss commented on src/main/java/com/artipie/docker/proxy/ProxyBlob.java
> +                    )).toCompletableFuture();
@g4s8 Done

2021-11-22 07:44 UTC, kirill-h5i commented
@andreoss please check CI logs, it fails

2021-11-23 19:52 UTC, andreoss commented
@kirill-h5i Done, sorry for the delay

2021-11-24 05:32 UTC, g4s8 approved these changes
@andreoss thanks

2021-11-24 05:32 UTC, merged