(#138) - Support for canceling upload
artipie/docker-adapter pull request #502
Opened 2021-12-11 19:32 UTC by andreoss

Per #138 

-

2021-12-14 05:46 UTC, g4s8 requested changes
@andreoss thanks, please check my comments

2021-12-14 05:46 UTC, g4s8 commented on src/main/java/com/artipie/docker/http/UploadEntity.java
> +                this.docker.repo(name).uploads().get(uuid).thenApply(
You can use `.thenCompose` to join `CompletableFuture`

2021-12-14 05:46 UTC, g4s8 commented on src/main/java/com/artipie/docker/http/UploadEntity.java
> +                        upload -> new AsyncResponse(
No need to wrap with second `AsyncReponse`

2021-12-14 05:46 UTC, g4s8 commented on src/main/java/com/artipie/docker/http/UploadEntity.java
> +                                    new ContentLength("0"),
Is it required by Docker API spec to put zero content length here?

2021-12-15 02:13 UTC, andreoss commented on src/main/java/com/artipie/docker/http/UploadEntity.java
> +                                    new ContentLength("0"),
@g4s8 No. Removed.

2021-12-15 07:39 UTC, g4s8 approved these changes
@andreoss thanks

2021-12-15 07:39 UTC, merged