#148 Store upload start date
artipie/docker-adapter pull request #503
Opened 2021-12-19 11:08 UTC by dgarus

Closes #148 
Upload starting date is saved in storage using the upload started key.

2021-12-22 13:17 UTC, olenagerasimova requested changes
@dgarus thanks, just one small suggestion

2021-12-22 13:17 UTC, olenagerasimova commented on src/test/java/com/artipie/docker/asto/AstoUploadTest.java
> +                        .thenCompose(PublisherAs::bytes)
@dgarus `PublisherAs` has `string` and `asciiString` methods, they can be used instead of calling string contactor

2021-12-23 08:59 UTC, dgarus commented
@olenagerasimova thank you!
I fixed your comment.

2021-12-23 09:00 UTC, olenagerasimova approved these changes
@dgarus thanks

2021-12-23 09:00 UTC, merged